---
title: "debugging"
date: 2018-02-15T15:17:57+01:00
draft: false
image: "debugging.jpg"
categories: ["R"]
tags: ["R", "debugging"]
---



<div id="what-is-debugging-and-why-would-use-use-it" class="section level2">
<h2>1. What is debugging and why would use use it?</h2>
<ul>
<li><p>According to <a href="https://en.wikipedia.org/wiki/Debugging">Wikipedia</a>, “Debugging is the process of finding and resolving defects or problems within a computer program that prevent correct operation of computer software or a system”.</p></li>
<li><p>R provides a couple of useful functions, which may be used not only for debugging purposes, but also for testing and even developing code.</p></li>
<li><p>All the functions present below are already available within basic packages (no installation required).</p></li>
</ul>
</div>
<div id="functions-frequently-used-for-debugging-purposes" class="section level2">
<h2>2. Functions frequently used for debugging purposes</h2>
<ul>
<li><h3 id="browser"><code>browser()</code></h3></li>
</ul>
<p>Rarely used directly, but important to understand how <code>debug()</code> works.</p>
<p>A short example:</p>
<p>Let’s say that function <code>my_function</code> returns an error. (In this case we cause an error intentionally.)</p>
<pre class="r"><code>my_function &lt;- function(x) {
  print(x)
  stop(&quot;This is an error.&quot;)
  print(x + 10)
}
my_function(x = 2)</code></pre>
<pre><code>## [1] 2</code></pre>
<pre><code>## Error in my_function(x = 2): This is an error.</code></pre>
<p>In order to find out where exactly the error occured, i.e. which statement caused it, we may enter the function’s body and run the statements line by line.</p>
<pre class="r"><code>my_function &lt;- function(x) {
  browser()  # just add this line of code into your function&#39;s definition 
  print(x)
  stop(&quot;This is an error.&quot;)
  print(x + 10)
}
my_function(x = 2)</code></pre>
<p>Right now you are in <code>my_function()</code>’s environment, which you can check by typing <code>environment()</code> or <code>ls()</code>. You can also see that the prompt has changed. Type <kbd>n</kbd> until you get to the line of code which produces an error.</p>
<p><em>Tip</em>: To skip a loop, type <kbd>c</kbd>.</p>
<p>To quit <code>browser()</code> earlier, type <kbd>q</kbd> and hit <kbd>Enter</kbd>.</p>
<ul>
<li><h3 id="debug-undebug-and-debugonce"><code>debug()</code>, <code>undebug()</code> and <code>debugonce()</code></h3></li>
</ul>
<p>Or the most useful debugging functions.</p>
<p>Let’s assume that you invoke a function inside of a function:</p>
<pre class="r"><code>my_inside_function &lt;- function(x_inside) {
  print(paste(&quot;x_inside: &quot;, x_inside + 10))
  print(&quot;after error&quot;)
}
my_function &lt;- function(x) {
  print(x)
  my_inside_function(&quot;some text&quot;)
  print(x + 10)
}
my_function(x = 2)</code></pre>
<pre><code>## [1] 2</code></pre>
<pre><code>## Error in x_inside + 10: non-numeric argument to binary operator</code></pre>
<p>which produces an error. You don’t know yet where exactly the error ocurred, so now you should write:</p>
<pre class="r"><code>debug(my_function)
my_function(x = 2)</code></pre>
<p>to start searching for the bug right from the top function. A new, weird-looking prompt appears: it is the same prompt as invoked by the <code>browser()</code> function, inside <code>my_function</code>. Type <code>ls()</code> and you will see that you actually <em>are</em> inside of <code>my_function</code>’s environment. Hit <kbd>n</kbd> a couple of times until you reach the error. You can see that it was <code>my_inside_function</code> that caused an error. Debugging <code>my_inside_function</code> will lead you straight to the statement which caused an error, but before entering <code>my_inside_function</code>, stop observing <code>my_function</code>:</p>
<pre class="r"><code>undebug(my_function)</code></pre>
<p>And then debug <code>my_inside_function</code>:</p>
<pre class="r"><code>debug(my_inside_function)
my_function(x = 2)</code></pre>
<p>After you find an error, don’t forget to stop observing the function:</p>
<pre class="r"><code>undebug(my_inside_function)</code></pre>
<p>You can also use <code>debugonce()</code>, the name of which is rather self-explanatory.</p>
<ul>
<li><h3 id="traceback"><code>traceback()</code></h3></li>
</ul>
<p>A quick view of where the bug may come from.</p>
<p>(from R docs)</p>
<p>Our example code:</p>
<pre class="r"><code>foo &lt;- function(x) { print(1); bar(2) }
bar &lt;- function(x) { x + a.variable.which.does.not.exist }
foo(2)</code></pre>
<pre><code>## [1] 1</code></pre>
<pre><code>## Error in bar(2): object &#39;a.variable.which.does.not.exist&#39; not found</code></pre>
<p>produces a strange error.</p>
<pre class="r"><code>traceback()
## End(Not run)
## 2: bar(2)
## 1: foo(2)</code></pre>
<p>As you can see, <code>traceback()</code> immediately points at the line where the error occured.</p>
<ul>
<li><h3 id="other-debugging-functions">Other debugging functions</h3></li>
</ul>
<p>There are two other functions that may be used for debugging, but as they are rarely used, I will not describe them in detail.</p>
<ul>
<li><p><code>trace()</code></p></li>
<li><p><code>recover()</code></p></li>
</ul>
</div>
<div id="useful-links" class="section level2">
<h2>3. Useful links:</h2>
<ul>
<li>A good tutorial is available <a href="https://www.youtube.com/watch?v=-yy_3htRHdU">here</a>.</li>
<li>A good article about debugging in R is available <a href="http://seananderson.ca/2013/08/23/debugging-r.html">here</a>.</li>
</ul>
</div>
